ambassador:
  rollouts:
    annotations:
      getambassador.io/rolloutId: cffc359d-0c86-4480-82e8-8a704c712d7e
    image:
      repository: docker.io/hashicorp/http-echo
      tag: latest
    replicas: 2
    steps:
    - setWeight: 10
    - pause:
        duration: 60
    - setWeight: 20
    - pause:
        duration: 60
    - setWeight: 30
    - pause:
        duration: 60
    - setWeight: 40
    - pause:
        duration: 60
    - setWeight: 50
    - pause:
        duration: 60
    - setWeight: 60
    - pause:
        duration: 60
    - setWeight: 70
    - pause:
        duration: 60
    - setWeight: 80
    - pause:
        duration: 60
    - setWeight: 90
    - pause:
        duration: 60
    - setWeight: 100
    - pause:
        duration: 60
