ambassador:
  rollouts:
    annotations:
      getambassador.io/rolloutId: fb4b4607-98a6-4b65-9514-796526a55f06
    image:
      repository: docker.io/hashicorp/http-echo
      tag: 0.2.1
    replicas: 2
    steps:
    - setWeight: 10
    - pause:
        duration: 720
    - setWeight: 20
    - pause:
        duration: 720
    - setWeight: 30
    - pause:
        duration: 720
    - setWeight: 40
    - pause:
        duration: 720
    - setWeight: 50
    - pause:
        duration: 720
    - setWeight: 60
    - pause:
        duration: 720
    - setWeight: 70
    - pause:
        duration: 720
    - setWeight: 80
    - pause:
        duration: 720
    - setWeight: 90
    - pause:
        duration: 720
    - setWeight: 100
    - pause:
        duration: 720
