ambassador:
  rollouts:
    annotations:
      getambassador.io/rolloutId: 669c052a-2aa1-4cc0-a6dc-5140dc15e358
    image:
      repository: docker.io/hashicorp/http-echo
      tag: 0.2.3
    replicas: 2
    steps:
    - setWeight: 10
    - pause:
        duration: 60
    - setWeight: 20
    - pause:
        duration: 60
    - setWeight: 30
    - pause:
        duration: 60
    - setWeight: 40
    - pause:
        duration: 60
    - setWeight: 50
    - pause:
        duration: 60
    - setWeight: 60
    - pause:
        duration: 60
    - setWeight: 70
    - pause:
        duration: 60
    - setWeight: 80
    - pause:
        duration: 60
    - setWeight: 90
    - pause:
        duration: 60
    - setWeight: 100
    - pause:
        duration: 60
