ambassador:
  rollouts:
    annotations:
      getambassador.io/rolloutId: 30be051b-b42a-4ca2-ad07-ecfe9913a401
    image:
      repository: docker.io/hashicorp/http-echo
      tag: 0.2.1
    replicas: 2
    steps:
    - setWeight: 10
    - pause:
        duration: 12
    - setWeight: 20
    - pause:
        duration: 12
    - setWeight: 30
    - pause:
        duration: 12
    - setWeight: 40
    - pause:
        duration: 12
    - setWeight: 50
    - pause:
        duration: 12
    - setWeight: 60
    - pause:
        duration: 12
    - setWeight: 70
    - pause:
        duration: 12
    - setWeight: 80
    - pause:
        duration: 12
    - setWeight: 90
    - pause:
        duration: 12
    - setWeight: 100
    - pause:
        duration: 12
