apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "echo.fullname" . }}
  {{- with .Values.ambassador.rollouts.annotations }}
  annotations:
    {{- toYaml . | nindent 4}}
  {{- end}}
spec:
    replicas: {{ .Values.ambassador.rollouts.replicas }}
    revisionHistoryLimit: 5
    strategy:
      canary:
        canaryService: {{ include "echo.fullname" . }}-canary
        stableService: {{ include "echo.fullname" . }}-stable
        {{- with .Values.ambassador.rollouts.trafficMappings }}
        trafficRouting:
          ambassador:
            mappings:
            {{- toYaml . | nindent 10 }}
        {{- end}}
        {{- with .Values.ambassador.rollouts.steps }}
        steps:
        {{- toYaml . | nindent 8}}
        {{- end}}
    template:
      spec:
        containers:
          - name: {{ .Chart.Name }}
            securityContext:
              {{- toYaml .Values.securityContext | nindent 12 }}
            image: "{{ .Values.ambassador.rollouts.image.repository }}:{{ .Values.ambassador.rollouts.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.imagePullPolicy }}
            resources:
              {{- toYaml .Values.resources | nindent 12 }}
        # ...
        # The rest of the file is omitted for simplicity.