---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  {{- with .Values.ambassador.rollouts.annotations }}
  annotations:
    {{- toYaml . | nindent 4}}
  {{- end}}
  name: {{ include "echo.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ include "echo.fullname" . }}
  replicas: {{ .Values.ambassador.rollouts.replicas }}
  revisionHistoryLimit: 5
  strategy:
    canary:
      canaryService: {{ include "echo.fullname" . }}-canary
      stableService: {{ include "echo.fullname" . }}
      {{- with .Values.ambassador.rollouts.trafficMappings }}
      trafficRouting:
        ambassador:
          mappings:
          {{- toYaml . | nindent 10 }}
      {{- end}}
      {{- with .Values.ambassador.rollouts.steps }}
      steps:
      {{- toYaml . | nindent 8}}
      {{- end}}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: echo
    spec:
      containers:
      - args:
        - -text=VERSION 3
        - -listen=:8080
        image: hashicorp/http-echo:0.2.3
        imagePullPolicy: Always
        name: echo-v1
        ports:
        - containerPort: 8080
        resources: {}
...