---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "echo.fullname" . }}
  name: {{ include "echo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    a8r.io/description: Echo service
    a8r.io/owner: Ambassador Labs
    a8r.io/documentation: https://www.getambassador.io/docs/cloud/latest/service-catalog/howtos/rollout/
    a8r.io/repository: git@github.com:knlambert/ambassador-rollouts-charts.git
    a8r.io/support: https://a8r.io/Slack
    a8r.io/rollouts.scm.path: charts/echo
    a8r.io/rollouts.scm.branch: main
    a8r.io/rollouts.image-repo.type: dockerhub
    a8r.io/rollouts.image-repo.name: hashicorp/http-echo
    a8r.io/rollouts.deployment: echo
    a8r.io/rollouts.mappings: echo
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ include "echo.fullname" . }}
...

