---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "echo.fullname" . }}
  name: {{ include "echo.fullname" . }}-canary
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ include "echo.fullname" . }} 
...
---